name: Build with MinGW
on:
    push:
        branches:
            - main
permissions:
    contents: write
jobs:
    build-with-gcc:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up MinGW
              uses: egor-tensin/setup-mingw@v2
              with:
                  platform: x64

            - name: Build
              run: |
                  g++ example.cpp -lgdi32 -lcomctl32 -luser32 -o program.exe
